export const blockTimes = {
  "ethereum-mainnet": 15,
  "ethereum-goerli": 15,
  "arbitrum-mainnet": 15,
  "arbitrum-goerli": 15,
  "binance-testnet": 3,
  "binance-mainnet": 3,
  "fantom-testnet": 1,
  "fantom-mainnet": 1,
  "avalanche-fuji": 3,
  "avalanche-mainnet": 3,
  "polygon-mumbai": 2,
  "polygon-mainnet": 2,
  "aurora-testnet": 1,
  "aurora-mainnet": 1,
};
